# OpenAPI 3.0 Specification
# Overcast Video Classroom API
# Version: 1.0.0

openapi: 3.0.3
info:
  title: Overcast Video Classroom API
  description: |
    REST API for the Overcast Video Classroom application.
    Provides cohort listing, instructor authentication, and Daily.co token generation.
  version: 1.0.0
  contact:
    name: Overcast Team

servers:
  - url: http://localhost:3000/api
    description: Local development
  - url: https://overcast.vercel.app/api
    description: Production (Vercel)

tags:
  - name: Cohorts
    description: Cohort classroom operations
  - name: Authentication
    description: Instructor authentication
  - name: Daily
    description: Daily.co integration

paths:
  /cohorts:
    get:
      summary: List all cohorts
      description: Returns the list of all 6 configured cohorts with their metadata.
      operationId: getCohorts
      tags:
        - Cohorts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  cohorts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Cohort'
              example:
                cohorts:
                  - id: "cohort-1"
                    name: "Cohort 1"
                    image: "/images/cohorts/cohort-1.jpg"
                    description: "AI Engineering Fundamentals - Week 1"

  /cohorts/{cohortId}:
    get:
      summary: Get cohort by ID
      description: Returns a single cohort by its unique identifier.
      operationId: getCohortById
      tags:
        - Cohorts
      parameters:
        - name: cohortId
          in: path
          required: true
          schema:
            type: string
          example: "cohort-1"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cohort'
        '404':
          description: Cohort not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      summary: Instructor login
      description: |
        Authenticates an instructor using username and password.
        On success, sets an HTTP-only cookie with a JWT token.
      operationId: instructorLogin
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          headers:
            Set-Cookie:
              schema:
                type: string
              description: HTTP-only cookie with instructor token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/logout:
    post:
      summary: Instructor logout
      description: Clears the instructor authentication cookie.
      operationId: instructorLogout
      tags:
        - Authentication
      responses:
        '200':
          description: Logout successful
          headers:
            Set-Cookie:
              schema:
                type: string
              description: Clears the instructor token cookie
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true

  /auth/verify:
    get:
      summary: Verify instructor session
      description: |
        Checks if the current user has a valid instructor session.
        Used to restore instructor mode on page refresh.
      operationId: verifyInstructor
      tags:
        - Authentication
      responses:
        '200':
          description: Session status
          content:
            application/json:
              schema:
                type: object
                properties:
                  isAuthenticated:
                    type: boolean
                  role:
                    type: string
                    enum: [instructor, student]
              examples:
                authenticated:
                  value:
                    isAuthenticated: true
                    role: instructor
                notAuthenticated:
                  value:
                    isAuthenticated: false
                    role: student

  /daily/token:
    post:
      summary: Generate Daily meeting token
      description: |
        Creates a Daily.co meeting token for joining a room.
        Instructor tokens include owner permissions (mute, kick, etc).
      operationId: createDailyToken
      tags:
        - Daily
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DailyTokenRequest'
      responses:
        '200':
          description: Token generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DailyTokenResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Daily.co API error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Cohort:
      type: object
      required:
        - id
        - name
        - image
        - description
      properties:
        id:
          type: string
          description: Unique identifier
          example: "cohort-1"
        name:
          type: string
          description: Display name
          example: "Cohort 1"
        image:
          type: string
          description: Path to cohort image
          example: "/images/cohorts/cohort-1.jpg"
        description:
          type: string
          description: Brief cohort description
          example: "AI Engineering Fundamentals - Week 1"
        capacity:
          type: integer
          description: Maximum participants (optional)
          example: 50

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          minLength: 1
          example: "instructor"
        password:
          type: string
          minLength: 8
          format: password
          example: "********"

    LoginResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Login successful"

    DailyTokenRequest:
      type: object
      required:
        - roomName
        - userName
      properties:
        roomName:
          type: string
          description: Daily.co room name
          example: "cohort-1"
        userName:
          type: string
          description: Display name for the participant
          example: "John Doe"
        isInstructor:
          type: boolean
          description: Whether to grant owner permissions
          default: false

    DailyTokenResponse:
      type: object
      properties:
        token:
          type: string
          description: Daily.co meeting token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        roomUrl:
          type: string
          description: Full room URL
          example: "https://overcast.daily.co/cohort-1"

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "Invalid credentials"
        code:
          type: string
          description: Error code
          example: "AUTH_FAILED"

